[package]
name = "todoli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.4"
thiserror = "1.0.58"
tokio = "1.37.0"

[dev-dependencies]
anyhow = "1.0.82"

